stages:
  prepare:
    cmd: C:/Users/CONDA/python.exe src/prepare.py
    deps:
    - src/prepare.py
    outs:
    - data

  train:
    cmd: C:/Users/CONDA/python.exe src/train.py data
    deps:
    - data
    - src/train.py
    params:
    - train.epochs
metrics:
- plots/metrics.json
- custom_dir/metrics.json
plots:
- plots/plots/metrics:
    x: step
- custom_dir/plots/metrics:
    x: step
